import Head from 'next/head';

import HeroSection from '../components/hero/hero';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Fashionee</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
    </>
  );
}
